version: 0.2

env:
  variables:
    REPOSITORY_URI: 427914668880.dkr.ecr.us-east-1.amazonaws.com/ecs-gameday-app

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 427914668880.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t ecs-app .
      - docker tag ecs-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json